.\" Manpage for opendlv-sim-rhino-can
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-sim-rhino-can 1 "04 March 2017" "0.8.10" "opendlv-sim-rhino-can man page"

.SH NAME
opendlv-sim-rhino-can \- This tool interfaces with the Revere Rhino truck.



.SH SYNOPSIS
.B opendlv-sim-rhino-can --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-sim-rhino-can --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

