.\" Manpage for opendlv-proxy-rhino-cloud
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-proxy-rhino-cloud 1 "26 September 2017" "0.1.4" "opendlv-proxy-rhino-cloud man page"

.SH NAME
opendlv-proxy-rhino-cloud \- This tool interfaces with the Revere Rhino truck.



.SH SYNOPSIS
.B opendlv-proxy-rhino-cloud --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-rhino-cloud --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

